[project]
protostar-version = "0.13.0"

[contracts]
ENS = ["min_ens/src"]
ERC20 = ["min_erc20/src"]
ERC721 = ["min_erc721/src"]
TOKEN_SALE = ["min_token_sale/src"]
MIN_AMM = ["min_amm/src"]
MIN_COMMIT_REVEAL = ["min_commit_reveal/src"]
MIN_ACCOUNT_MULTICALL = ["min_account_multicall/src"]
MIN_MULTISIG = ["min_multisig/src"]
MIN_MESSAGING_BRIDGE = ["min_messaging_bridge/L2/src"]